# Generated by Django 4.0.5 on 2022-07-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_track_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_title',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
