# Generated by Django 4.0.5 on 2022-07-05 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_album', to='albums.artist'),
        ),
    ]
