# Generated by Django 4.0.5 on 2022-07-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0012_album_new_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='new_artist',
            new_name='add_artist_name',
        ),
    ]
