# Generated by Django 4.0.5 on 2022-07-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_rename_new_artist_album_add_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='add_artist_name',
        ),
    ]
