# Generated by Django 4.0.5 on 2022-07-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_remove_album_add_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='add_artist_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
